---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ice36-ubuntu1804
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      ice36-ubuntu1804:
        ice_install_devel: false
        ice_binaries_symlink_dest: /usr/local/bin
scenario:
  name: ice36-ubuntu1804
  converge_sequence:
    - converge
verifier:
  name: testinfra
  lint:
    name: flake8
