---
name: Build
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ice36all
          - ice36minimal
          - ice36-ubuntu1804
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -mpip install --upgrade wheel "ome-ansible-molecule<0.5"
      - name: Run tests
        run: molecule test -s ${{ matrix.scenario }}

  publish-galaxy:
    name: Galaxy
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
